package generator

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/types"
	"strings"

	"github.com/99designs/gqlgen/codegen/config"
	"github.com/99designs/gqlgen/codegen/templates"

	"github.com/gqlgo/gqlgenc/clientgenv2"
	gqlgencConfig "github.com/gqlgo/gqlgenc/config"
)

//go:embed template.gotpl
var federationTemplate string

// RenderFederationTemplate renders the federation client template.
// It mirrors clientgenv2.RenderTemplate but uses the federation-specific template.
// urlMode is "baked" (default) or "enum"; it controls which NewClient signature
// is generated. See config.Config.URLMode for the full description.
func RenderFederationTemplate(
	cfg *config.Config,
	fragments []*clientgenv2.Fragment,
	operations []*clientgenv2.Operation,
	operationResponses []*clientgenv2.OperationResponse,
	structSources []*clientgenv2.StructSource,
	generateCfg *gqlgencConfig.GenerateConfig,
	client config.PackageConfig,
	planSpecs map[string]string,
	urlMode string,
) error {
	if urlMode == "" {
		urlMode = "baked"
	}
	g := &genGettersGenerator{clientPackageName: client.Package}

	err := templates.Render(templates.Options{
		PackageName: client.Package,
		Filename:    client.Filename,
		Template:    federationTemplate,
		Data: map[string]any{
			"Fragment":            fragments,
			"Operation":           operations,
			"OperationResponse":   operationResponses,
			"GenerateClient":      generateCfg.ShouldGenerateClient(),
			"StructSources":       structSources,
			"ClientInterfaceName": generateCfg.GetClientInterfaceName(),
			"PlanSpecs":           planSpecs,
			"URLModeEnum":         urlMode == "enum",
		},
		Packages:   cfg.Packages,
		PackageDoc: "// Code generated by github.com/StevenACoffman/defederator, DO NOT EDIT.\n",
		Funcs: map[string]any{
			"genGetters":           g.genFunc(),
			"genConversionGetters": g.conversionGettersFunc(fragments),
		},
	})
	if err != nil {
		return fmt.Errorf("%s generating failed: %w", client.Filename, err)
	}
	return nil
}

// genGettersGenerator is a local copy of clientgenv2.GenGettersGenerator.
// clientgenv2 does not export it, so we duplicate the ~80 lines here.
type genGettersGenerator struct {
	clientPackageName string
}

func (g *genGettersGenerator) genFunc() func(name string, p types.Type) string {
	return func(name string, p types.Type) string {
		st, ok := p.(*types.Struct)
		if !ok {
			return ""
		}
		var buf bytes.Buffer
		for i := range st.NumFields() {
			field := st.Field(i)
			ret := g.returnTypeName(field.Type(), false)
			buf.WriteString("func (t *" + name + ") Get" + field.Name() + "() " + ret + "{\n")
			buf.WriteString("if t == nil {\n t = &" + name + "{}\n}\n")
			ptr := ""
			if _, ok := field.Type().(*types.Named); ok {
				ptr = "&"
			}
			buf.WriteString("return " + ptr + "t." + field.Name() + "\n}\n")
		}
		return buf.String()
	}
}

func (g *genGettersGenerator) returnTypeName(t types.Type, nested bool) string {
	switch it := t.(type) {
	case *types.Basic:
		return it.String()
	case *types.Pointer:
		return "*" + g.returnTypeName(it.Elem(), true)
	case *types.Slice:
		return "[]" + g.returnTypeName(it.Elem(), true)
	case *types.Named:
		s := strings.Split(it.String(), ".")
		name := s[len(s)-1]
		if it.Obj().Parent() != nil && it.Obj().Pkg().Name() != g.clientPackageName {
			name = fmt.Sprintf("%s.%s", it.Obj().Pkg().Name(), it.Obj().Name())
		}
		if nested {
			return name
		}
		return "*" + name
	case *types.Interface:
		return "any"
	case *types.Map:
		return "map[" + g.returnTypeName(it.Key(), true) + "]" + g.returnTypeName(it.Elem(), true)
	case *types.Alias:
		return g.returnTypeName(it.Underlying(), nested)
	default:
		return fmt.Sprintf("%T----", it)
	}
}

func (g *genGettersGenerator) conversionGettersFunc(allFragments []*clientgenv2.Fragment) func(ownerName string, spreads []*clientgenv2.SpreadFragmentInfo) string {
	fragmentMap := make(map[string]*clientgenv2.Fragment, len(allFragments))
	for _, f := range allFragments {
		fragmentMap[f.Name] = f
	}
	return func(ownerName string, spreads []*clientgenv2.SpreadFragmentInfo) string {
		if len(spreads) == 0 {
			return ""
		}
		var buf bytes.Buffer
		for _, spread := range spreads {
			frag, ok := fragmentMap[spread.Name]
			if !ok {
				continue
			}
			targetStruct, ok := frag.Type.(*types.Struct)
			if !ok {
				continue
			}
			targetName := g.typeName(spread.Type)
			buf.WriteString("func (t *" + ownerName + ") Get" + targetName + "() *" + targetName + " {\n")
			buf.WriteString("if t == nil {\n t = &" + ownerName + "{}\n}\n")
			buf.WriteString("return &" + targetName + "{\n")
			g.writeStructLiteral(&buf, targetStruct, "t")
			buf.WriteString("}\n}\n")
		}
		return buf.String()
	}
}

func (g *genGettersGenerator) writeStructLiteral(buf *bytes.Buffer, st *types.Struct, src string) {
	for i := range st.NumFields() {
		f := st.Field(i)
		if nested := underlyingStruct(f.Type()); nested != nil {
			buf.WriteString(f.Name() + ": " + g.typeName(f.Type()) + "{\n")
			g.writeStructLiteral(buf, nested, src+"."+f.Name())
			buf.WriteString("},\n")
		} else {
			buf.WriteString(f.Name() + ": " + src + "." + f.Name() + ",\n")
		}
	}
}

func (g *genGettersGenerator) typeName(t types.Type) string {
	switch it := t.(type) {
	case *types.Named:
		s := strings.Split(it.String(), ".")
		return s[len(s)-1]
	case *types.Pointer:
		return g.typeName(it.Elem())
	default:
		return t.String()
	}
}

func underlyingStruct(t types.Type) *types.Struct {
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return nil
	}
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return nil
	}
	return st
}
