package generator

import (
	"bytes"
	_ "embed"
	"fmt"
	"go/types"
	"strings"
	"unicode"

	"github.com/99designs/gqlgen/codegen/config"
	"github.com/99designs/gqlgen/codegen/templates"
	"github.com/gqlgo/gqlgenc/clientgenv2"
	gqlgencConfig "github.com/gqlgo/gqlgenc/config"
)

// EnumDef describes a single GraphQL enum to emit as a Go named-string type.
// The template renders one `type T string` declaration plus a `const ( … )` block
// and a `var AllT = []T{ … }` slice, matching genqlient's output.
type EnumDef struct {
	GoName      string
	GraphQLName string
	Description string
	Values      []EnumValueDef
}

// EnumValueDef is a single enum value: GraphQL wire name and Go constant name.
type EnumValueDef struct {
	GoName      string
	GraphQLName string
	Description string
}

// CommentLine renders an arbitrary string as a single-line Go comment payload by
// collapsing all whitespace (including newlines) to single spaces and stripping
// leading/trailing whitespace. Used so that multi-line GraphQL descriptions are
// safe to embed in generated `// …` enum/value doc comments without spilling
// out of the comment block.
func CommentLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// GoConstName converts a GraphQL enum value name (typically SCREAMING_SNAKE_CASE)
// into a Go constant suffix using genqlient's `goConstName` rules: each underscore
// is dropped, the character after each underscore (and the first character) is
// upper-cased, and all other characters are lower-cased. Identical input/output to
// `genqlient/generate/util.go`'s goConstName so generated code matches genqlient.
func GoConstName(s string) string {
	if strings.TrimLeft(s, "_") == "" {
		return s
	}
	var prev rune
	return strings.Map(func(r rune) rune {
		var ret rune
		switch {
		case r == '_':
			ret = -1
		case prev == '_' || prev == 0:
			ret = unicode.ToUpper(r)
		default:
			ret = unicode.ToLower(r)
		}
		prev = r
		return ret
	}, s)
}

//go:embed template.gotpl
var federationTemplate string

// genGettersGenerator is a local copy of clientgenv2.GenGettersGenerator.
// clientgenv2 does not export it, so we duplicate the ~80 lines here.
type genGettersGenerator struct {
	clientPackageName string
}

// inlineFragField pairs a Go struct field name with the concrete GraphQL type it
// represents via a graphql:"... on Type" tag.
type inlineFragField struct {
	goName   string // Go field name, e.g. "District"
	typeName string // concrete GraphQL type, e.g. "District"
}

// RenderFederationTemplate renders the federation client template.
// It mirrors clientgenv2.RenderTemplate but uses the federation-specific template.
// urlMode is "baked" (default) or "enum"; it controls which NewClient signature
// is generated. See config.Config.URLMode for the full description.
func RenderFederationTemplate(
	cfg *config.Config,
	fragments []*clientgenv2.Fragment,
	operations []*clientgenv2.Operation,
	operationResponses []*clientgenv2.OperationResponse,
	structSources []*clientgenv2.StructSource,
	generateCfg *gqlgencConfig.GenerateConfig,
	client config.PackageConfig,
	planSpecs map[string]string,
	urlMode string,
	enums []*EnumDef,
) error {
	if urlMode == "" {
		urlMode = "baked"
	}
	g := &genGettersGenerator{clientPackageName: client.Package}

	// Build response type map for entity fetch code generation.
	respTypeByName := make(map[string]types.Type, len(operationResponses))
	for _, or_ := range operationResponses {
		respTypeByName[or_.Name] = or_.Type
	}

	// Determine if any operation uses typed entity merge (controls json import).
	hasTypedEntityFetch := false
	for _, op := range operations {
		if specJSON := planSpecs[op.Name]; specJSON != "" {
			if respType := respTypeByName[op.ResponseStructName]; respType != nil {
				if g.genEntityFetch(
					op.Name,
					respType,
					templates.ToGo(op.ResponseStructName),
					specJSON,
				) != "" {
					hasTypedEntityFetch = true
					break
				}
			}
		}
	}

	// Determine if any response type needs a custom UnmarshalJSON (controls json import).
	hasInlineFragType := false
	for _, or_ := range operationResponses {
		if genUnmarshalJSONMethod(or_.Name, or_.Type) != "" {
			hasInlineFragType = true
			break
		}
	}

	err := templates.Render(templates.Options{
		PackageName: client.Package,
		Filename:    client.Filename,
		Template:    federationTemplate,
		Data: map[string]any{
			"Fragment":            fragments,
			"Operation":           operations,
			"OperationResponse":   operationResponses,
			"GenerateClient":      generateCfg.ShouldGenerateClient(),
			"StructSources":       structSources,
			"ClientInterfaceName": generateCfg.GetClientInterfaceName(),
			"PlanSpecs":           planSpecs,
			"URLModeEnum":         urlMode == "enum",
			"HasTypedEntityFetch": hasTypedEntityFetch || hasInlineFragType,
			"Enum":                enums,
		},
		Packages:   cfg.Packages,
		PackageDoc: "// Code generated by github.com/StevenACoffman/defederator, DO NOT EDIT.\n",
		Funcs: map[string]any{
			"genGetters":           g.genFunc(),
			"genConversionGetters": g.conversionGettersFunc(fragments),
			"genEntityFetch":       g.genEntityFetchFunc(operationResponses, planSpecs),
			"genUnmarshalJSON": func(name string, t types.Type) string {
				return genUnmarshalJSONMethod(name, t)
			},
			"commentLine": CommentLine,
		},
	})
	if err != nil {
		return fmt.Errorf("%s generating failed: %w", client.Filename, err)
	}
	return nil
}

func (g *genGettersGenerator) genFunc() func(name string, p types.Type) string {
	return func(name string, p types.Type) string {
		st, ok := p.(*types.Struct)
		if !ok {
			return ""
		}
		var buf bytes.Buffer
		for i := range st.NumFields() {
			field := st.Field(i)
			ret := g.returnTypeName(field.Type(), false)
			buf.WriteString("func (t *" + name + ") Get" + field.Name() + "() " + ret + "{\n")
			buf.WriteString("if t == nil {\n t = &" + name + "{}\n}\n")
			ptr := ""
			if _, ok := field.Type().(*types.Named); ok {
				ptr = "&"
			}
			buf.WriteString("return " + ptr + "t." + field.Name() + "\n}\n")
		}
		return buf.String()
	}
}

// resolveNamedTypeName returns the Go type name for a *types.Named, applying
// package qualification when the type lives outside clientPackageName.
func (g *genGettersGenerator) resolveNamedTypeName(it *types.Named, nested bool) string {
	s := strings.Split(it.String(), ".")
	name := s[len(s)-1]
	if it.Obj().Parent() != nil && it.Obj().Pkg().Name() != g.clientPackageName {
		name = fmt.Sprintf("%s.%s", it.Obj().Pkg().Name(), it.Obj().Name())
	}
	if nested {
		return name
	}
	return "*" + name
}

func (g *genGettersGenerator) returnTypeName(t types.Type, nested bool) string {
	switch it := t.(type) {
	case *types.Basic:
		return it.String()
	case *types.Pointer:
		return "*" + g.returnTypeName(it.Elem(), true)
	case *types.Slice:
		return "[]" + g.returnTypeName(it.Elem(), true)
	case *types.Named:
		return g.resolveNamedTypeName(it, nested)
	case *types.Interface:
		return "any"
	case *types.Map:
		return "map[" + g.returnTypeName(it.Key(), true) + "]" + g.returnTypeName(it.Elem(), true)
	case *types.Alias:
		return g.returnTypeName(it.Underlying(), nested)
	default:
		return fmt.Sprintf("%T----", it)
	}
}

func (g *genGettersGenerator) conversionGettersFunc(
	allFragments []*clientgenv2.Fragment,
) func(ownerName string, spreads []*clientgenv2.SpreadFragmentInfo) string {
	fragmentMap := make(map[string]*clientgenv2.Fragment, len(allFragments))
	for _, f := range allFragments {
		fragmentMap[f.Name] = f
	}
	return func(ownerName string, spreads []*clientgenv2.SpreadFragmentInfo) string {
		if len(spreads) == 0 {
			return ""
		}
		var buf bytes.Buffer
		for _, spread := range spreads {
			frag, ok := fragmentMap[spread.Name]
			if !ok {
				continue
			}
			targetStruct, ok := frag.Type.(*types.Struct)
			if !ok {
				continue
			}
			targetName := g.typeName(spread.Type)
			buf.WriteString(
				"func (t *" + ownerName + ") Get" + targetName + "() *" + targetName + " {\n",
			)
			buf.WriteString("if t == nil {\n t = &" + ownerName + "{}\n}\n")
			buf.WriteString("return &" + targetName + "{\n")
			g.writeStructLiteral(&buf, targetStruct, "t")
			buf.WriteString("}\n}\n")
		}
		return buf.String()
	}
}

func (g *genGettersGenerator) writeStructLiteral(buf *bytes.Buffer, st *types.Struct, src string) {
	for i := range st.NumFields() {
		f := st.Field(i)
		if nested := underlyingStruct(f.Type()); nested != nil {
			buf.WriteString(f.Name() + ": " + g.typeName(f.Type()) + "{\n")
			g.writeStructLiteral(buf, nested, src+"."+f.Name())
			buf.WriteString("},\n")
		} else {
			buf.WriteString(f.Name() + ": " + src + "." + f.Name() + ",\n")
		}
	}
}

func (g *genGettersGenerator) typeName(t types.Type) string {
	switch it := t.(type) {
	case *types.Named:
		s := strings.Split(it.String(), ".")
		return s[len(s)-1]
	case *types.Pointer:
		return g.typeName(it.Elem())
	default:
		return t.String()
	}
}

func underlyingStruct(t types.Type) *types.Struct {
	if ptr, ok := t.(*types.Pointer); ok {
		t = ptr.Elem()
	}
	named, ok := t.(*types.Named)
	if !ok {
		return nil
	}
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return nil
	}
	return st
}

// graphqlInlineFragType returns the concrete type name from a `graphql:"... on Type"`
// struct tag, or "" if the tag is absent or not in inline-fragment form.
func graphqlInlineFragType(tag string) string {
	const prefix = `graphql:"... on `
	i := strings.Index(tag, prefix)
	if i < 0 {
		return ""
	}
	rest := tag[i+len(prefix):]
	end := strings.IndexByte(rest, '"')
	if end < 0 {
		return ""
	}
	return rest[:end]
}

// genUnmarshalJSONMethod returns a custom UnmarshalJSON method for structName when t
// is a struct with at least one field carrying graphql:"... on Type" but no json: tag.
// Returns "" when no such field exists — the common case, so no method is emitted.
func genUnmarshalJSONMethod(structName string, t types.Type) string {
	st := unwrapToStruct(t)
	if st == nil {
		return ""
	}
	var frags []inlineFragField
	var typenameGoName string
	for i := range st.NumFields() {
		tag := st.Tag(i)
		goName := st.Field(i).Name()
		if parseJSONKey(tag) == "__typename" {
			typenameGoName = goName
			continue
		}
		// Inline fragment field: graphql:"... on Type" tag with no json: tag.
		if parseJSONKey(tag) == "" {
			if tn := graphqlInlineFragType(tag); tn != "" {
				frags = append(frags, inlineFragField{goName: goName, typeName: tn})
			}
		}
	}
	if len(frags) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("func (t *" + structName + ") UnmarshalJSON(data []byte) error {\n")
	b.WriteString("var _disc struct{ Typename *string `json:\"__typename\"` }\n")
	b.WriteString("if _err := json.Unmarshal(data, &_disc); _err != nil { return _err }\n")
	if typenameGoName != "" {
		b.WriteString("t." + typenameGoName + " = _disc.Typename\n")
	}
	b.WriteString("if _disc.Typename != nil {\n")
	b.WriteString("switch *_disc.Typename {\n")
	for _, f := range frags {
		b.WriteString("case \"" + f.typeName + "\":\n")
		b.WriteString(
			"if _err := json.Unmarshal(data, &t." + f.goName + "); _err != nil { return _err }\n",
		)
	}
	b.WriteString("}\n}\nreturn nil\n}\n")
	return b.String()
}
