// Package graphqlcompat provides a graphql.Client (genqlient's interface) backed
// by the defederator federation planner. Swap one constructor call; keep all
// existing genqlient-generated types and functions unchanged.
//
// Because genqlient delivers the query document at call time (not at startup),
// this package builds plans lazily on first use and caches them by operation name.
// For code generated by defederator, use the generated NewClient directly — it
// pre-builds plans at startup and does not pay this per-operation cold start.
package graphqlcompat

import (
	"context"
	"fmt"
	"net/http"
	"sync"

	"github.com/Khan/genqlient/graphql"
	"github.com/StevenACoffman/defederator/execengine"
	"github.com/StevenACoffman/gorouter/federation"
)

type client struct {
	sg        *federation.Supergraph
	http      *http.Client
	planCache sync.Map // opName string → *execengine.Plan
}

// NewClient returns a graphql.Client that routes all requests through the
// federation query planner instead of a gateway.
func NewClient(sg *federation.Supergraph, httpClient *http.Client) graphql.Client {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &client{sg: sg, http: httpClient}
}

func (c *client) MakeRequest(ctx context.Context, req *graphql.Request, resp *graphql.Response) error {
	if req.OpName == "" {
		return fmt.Errorf("graphqlcompat: anonymous operations are not supported")
	}

	v, ok := c.planCache.Load(req.OpName)
	if !ok {
		plan, err := federation.BuildPlan(c.sg, req.Query, req.OpName)
		if err != nil {
			return fmt.Errorf("graphqlcompat: plan %q: %w", req.OpName, err)
		}
		v, _ = c.planCache.LoadOrStore(req.OpName, planToExec(plan))
	}
	ep := v.(*execengine.Plan)

	// When genqlient pre-sets resp.Data to a typed pointer, pass it directly so
	// json.Unmarshal fills the concrete struct. When resp.Data is nil (bare callers),
	// pass &resp.Data so it is populated with map[string]any.
	dest := any(&resp.Data)
	if resp.Data != nil {
		dest = resp.Data
	}
	if err := execengine.ExecuteAndUnmarshal(ctx, ep, req.Variables, c.http, dest); err != nil {
		return fmt.Errorf("graphqlcompat: execute %q: %w", req.OpName, err)
	}
	return nil
}

// planToExec converts a resolved *federation.Plan to an *execengine.Plan by
// substituting *Subgraph pointers with URL strings.
func planToExec(plan *federation.Plan) *execengine.Plan {
	ep := &execengine.Plan{
		Fetches:       make([]execengine.Fetch, 0, len(plan.Fetches)),
		EntityFetches: make([]execengine.EntityFetch, 0, len(plan.EntityFetches)),
		Projection:    projectionToExec(plan.Projection),
	}
	for _, f := range plan.Fetches {
		ep.Fetches = append(ep.Fetches, execengine.Fetch{
			URL:       f.Subgraph.URL,
			Query:     f.Query,
			Variables: f.Variables,
		})
	}
	for _, ef := range plan.EntityFetches {
		ep.EntityFetches = append(ep.EntityFetches, execengine.EntityFetch{
			URL:            ef.Subgraph.URL,
			TypeName:       ef.TypeName,
			KeyFields:      ef.KeyFields,
			RequiresFields: ef.RequiresFields,
			Selection:      ef.Selection,
			ParentPath:     ef.ParentPath,
			IsParentList:   ef.IsParentList,
		})
	}
	return ep
}

func projectionToExec(proj []*federation.FieldProjection) []*execengine.FieldProjection {
	if len(proj) == 0 {
		return nil
	}
	out := make([]*execengine.FieldProjection, len(proj))
	for i, p := range proj {
		out[i] = &execengine.FieldProjection{
			Key:      p.Key,
			Children: projectionToExec(p.Children),
		}
	}
	return out
}
