// Code generated by defederator migrate. DO NOT EDIT.
// Regenerate: defederator migrate --force /srv/webapp/services/example
package cross_service

import (
	"context"
	"net/http"
	"net/url"

	"github.com/Khan/genqlient/graphql"
	"github.com/Khan/webapp/pkg/lib/defederatorcompat"
	"github.com/Khan/webapp/pkg/lib/errors"
	"github.com/Khan/webapp/pkg/lib/httpctx"
	"github.com/Khan/webapp/pkg/lib/service_discovery"
	"github.com/Khan/webapp/pkg/web"
	"github.com/Khan/webapp/pkg/web/gqlclient"
	defed "github.com/Khan/webapp/services/example/generated/defederator"
)

// federationCtx is the minimal context the per-request federation client needs:
// HTTP transport from the request context and service discovery for subgraph URL
// resolution. Use newFederationClient for handlers that propagate the caller's
// auth via the incoming HTTP transport. The test-compat path inside
// newFederationClient checks for gqlclient.KAContext at runtime — callers that
// happen to also satisfy gqlclient.KAContext (i.e. the full webapp ktx in
// tests) opt in via defederatorcompat.WithMode; callers without it (CLI tools,
// narrower contexts) fall through unaffected to the federation HTTP path.
type federationCtx interface {
	context.Context
	web.ServiceVersionContext
	httpctx.KAContext
	service_discovery.KAContext
}

// newFederationClient returns a FederationClient whose HTTP transport and subgraph
// URLs are resolved fresh from ctx on every operation call. In tests where the
// suite has called defederatorcompat.WithMode(ctx), per-operation calls dispatch
// through the gqlclient mock using the composed federated query — keeping existing
// gqlclient.Mux-based mocks working unchanged after migration from genqlient.
func newFederationClient(ctx federationCtx) defed.FederationClient {
	return defed.NewClientWithFactories(
		func(callCtx context.Context) *http.Client {
			if h, ok := callCtx.(httpctx.KAContext); ok {
				return h.HTTP()
			}
			return http.DefaultClient
		},
		func(callCtx context.Context, specJSON string) (*defed.Plan, error) {
			urls, err := exampleSubgraphURLs(callCtx, ctx.ServiceDiscovery())
			if err != nil {
				return nil, err
			}
			return defed.Resolve(specJSON, urls)
		},
		defed.WithGQLClientFor(func(callCtx context.Context) graphql.Client {
			// Return nil unless the test harness has opted in. Production never
			// sets the mode signal, so this branch is a no-op in prod.
			if !defederatorcompat.IsMode(callCtx) {
				return nil
			}
			if gc, ok := callCtx.(gqlclient.KAContext); ok {
				return gc.GraphQL().AsServiceAdmin()
			}
			return nil
		}),
	)
}

// _subgraphServices maps join__Graph enum names to service-discovery names.
// Pruned at migration time to the set of subgraphs this service's operations
// actually query.
var _subgraphServices = map[string]string{
	"CONTENT": "content",
	"USERS": "users",
}

// exampleSubgraphURLs builds the enum-name → HTTP-endpoint map by calling
// service discovery for each subgraph this service's operations touch.
func exampleSubgraphURLs(ctx context.Context, sd service_discovery.Client) (map[string]string, error) {
	urls := make(map[string]string, len(_subgraphServices))
	for enumName, svcName := range _subgraphServices {
		u, err := sd.EndpointForServiceWithVersion(ctx, svcName, "")
		if err != nil {
			return nil, errors.Wrap(err, "enumName", enumName, "svcName", svcName)
		}
		urls[enumName] = (&url.URL{
			Scheme: u.Scheme,
			Host:   u.Host,
			Path:   "/backend-graphql/",
		}).String()
	}
	return urls, nil
}
